version: '3.8'

services:
  learn-app:
    container_name: learn-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_REPO_URL: https://github.com/NIKHILSAI71/Learn.git
        BRANCH: master
      no_cache: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - N8N_WEBHOOK_URL=http://n8n-container:5678/webhook/learn
      - CODE_EXECUTION_TIMEOUT=${CODE_EXECUTION_TIMEOUT:-10000}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    volumes:
      - code-execution-temp:/tmp/code-execution
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - learn-network
    external_links:
      - n8n-container

volumes:
  code-execution-temp:
    driver: local

networks:
  learn-network:
    external: true
